### ISSUE TITLE
Add SSM support for CodeBuild actions

### ISSUE THREAD

**Issue by smuralee** [awslabs/aws-service-catalog-products#59]
**Current implementation**
* Actions need the code build project name to be hardcoded

```yaml
actions:
  ping-on-prem-host:
    type: codebuild
    project_name: ping-on-prem-host
    account_id: '0123456789010'
    region: 'eu-west-1'
    parameters:
      HOST_TO_PING:
        ssm:
          name: HOST_TO_PING
          region: eu-west-1
```

**Requested feature**
* Support SSM param for the `project_name` and `account_id`
```yaml
actions:
  ping-on-prem-host: 
    type: codebuild
    project_name: 
      ssm: 
        name: ping-on-prem-host
        region: eu-west-1
    account_id: 
      ssm: 
        name: ping-host-account-id
        region: eu-west-1
    region: eu-west-1
    parameters: 
      HOST_TO_PING: 
        ssm: 
          name: HOST_TO_PING
          region: eu-west-1
```
